### ISSUE TITLE
Bug report and UX suggestion: the reminders are too easy to miss

### ISSUE THREAD

**Issue by ZinaL88** [WinTenDev/rminder#8]
1. The reminders just pop up for a few seconds and then disappear. If I happened to look away, I might miss the message.
2. Sometimes it even didn't pop up notification. 

I like the concept and value of rminder, hope it will be better and more user-friendly. Thanks.

**Comment by Kholid060** [comment]
For the notification, I can't really do anything about it because there's no API for customizing the time for the notification to disappear and that's why there's a "next notification" label when you open the extension so user can know when the notification will appear, but if you have any other option to show the reminder message to the user I would consider to using it.
